import CrystalForestLeftImg from "../../images/zoneImages/CrystalForestLeft.png"
import CrystalForestRightImg from "../../images/zoneImages/CrystalForestRight.png"

export const zoneData = {
  CrystalForest: {
    regionSpecificData: {
      imgLeft: CrystalForestLeftImg,
      imgRight: CrystalForestRightImg,
    },
    spirePath: {
      name: "Spire Path",
      location: "/Zone/CrystalForest",
      exitOne: "/HUB",
      exitTwo: "Vinefall",
      exitThree: "The Ruined Stairway",
      exitFour: "The Rootway",  
    },
    vineFall: {
      name: "Vinefall",
      location: "/Zone/CrystalForest",
      exitOne: "Spire Path",
      exitTwo: "Underbrush",
      exitThree: "The Climb",
      exitFour: "None",  
    },
    ruinedStairway: {
      name: "The Ruined Stairway",
      location: "/Zone/CrystalForest",
      exitOne: "Spire Path",
      exitTwo: "Shimmering Valley",
      exitThree: "None",
      exitFour: "None",  
    },
    shimmeringValley: {
      name: "Shimmering Valley",
      location: "/Zone/CrystalForest",
      exitOne: "The Ruined Stairway",
      exitTwo: "Petrified Gate",
      exitThree: "None",
      exitFour: "None",  
    },
    petrifiedGate: {
      name: "Petrified Gate",
      location: "/Zone/CrystalForest",
      exitOne: "Shimmering Valley",
      exitTwo: "None",
      exitThree: "None",
      exitFour: "None",  
    },
    rootway: {
      name: "The Rootway",
      location: "/Zone/CrystalForest",
      exitOne: "Spire Path",
      exitTwo: "Rotting River",
      exitThree: "Crystal Rat's Domain",
      exitFour: "None",  
    },
    crystalRatLairOne: {
      name: "Crystal Rat's Domain",
      location: "/Zone/CrystalForest",
      exitOne: "The Rootway",
      exitTwo: "Crystal Rat's Hive",
      exitThree: "None",
      exitFour: "None",  
    },
    crystalRatLairTwo: {
      name: "Crystal Rat's Hive",
      location: "/Zone/CrystalForest",
      exitOne: "Crystal Rat's Domain",
      exitTwo: "Crystal Rat's Armory",
      exitThree: "None",
      exitFour: "None",  
    },
    crystalRatLairThree: {
      name: "Crystal Rat's Armory",
      location: "/Zone/CrystalForest",
      exitOne: "Crystal Rat's Hive",
      exitTwo: "Throne of the Crystal Rat",
      exitThree: "None",
      exitFour: "None",  
    },
    crystalRatLairFour: {
      name: "Throne of the Crystal Rat",
      location: "/Zone/CrystalForest",
      exitOne: "Crystal Rat's Armory",
      exitTwo: "None",
      exitThree: "None",
      exitFour: "None",  
    },
    rottingRiver: {
      name: "Rotting River",
      location: "/Zone/CrystalForest",
      exitOne: "The Rootway",
      exitTwo: "Deeprot",
      exitThree: "None",
      exitFour: "None",  
    },
    deeprot: {
      name: "Deeprot",
      location: "/Zone/CrystalForest",
      exitOne: "Rotting River",
      exitTwo: "Desecrated Core",
      exitThree: "None",
      exitFour: "None",  
    },
    desecratedCore: {
      name: "Desecrated Core",
      location: "/Zone/CrystalForest",
      exitOne: "Deeprot",
      exitTwo: "None",
      exitThree: "None",
      exitFour: "None",  
    },
    underbrush: {
      name: "Underbrush",
      location: "/Zone/CrystalForest",
      exitOne: "Vinefall",
      exitTwo: "Vinemother's Garden",
      exitThree: "None",
      exitFour: "None",  
    },
    vinemotherGarden: {
      name: "Vinemother's Garden",
      location: "/Zone/CrystalForest",
      exitOne: "Underbrush",
      exitTwo: "Vinemother's Grove",
      exitThree: "None",
      exitFour: "None",  
    },
    vinemotherGrove: {
      name: "Vinemother's Grove",
      location: "/Zone/CrystalForest",
      exitOne: "Vinemother's Garden",
      exitTwo: "Twisted Vines of the Vinemother",
      exitThree: "None",
      exitFour: "None",  
    },
    vinemotherTwistedVines: {
      name: "Twisted Vines of the Vinemother",
      location: "/Zone/CrystalForest",
      exitOne: "Vinemother's Grove",
      exitTwo: "None",
      exitThree: "None",
      exitFour: "None",  
    },
    theClimb: {
      name: "The Climb",
      location: "/Zone/CrystalForest",
      exitOne: "Vinefall",
      exitTwo: "Crystal Top",
      exitThree: "None",
      exitFour: "None",  
    },
    crystalTop: {
      name: "Crystal Top",
      location: "/Zone/CrystalForest",
      exitOne: "The Climb",
      exitTwo: "Ascension Rise",
      exitThree: "None",
      exitFour: "None",  
    },
    ascensionRise: {
      name: "Ascension Rise",
      location: "/Zone/CrystalForest",
      exitOne: "Crystal Top",
      exitTwo: "None",
      exitThree: "None",
      exitFour: "None",  
    },

  }
}